include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/main_firebase.dart
    - lib/main_no_auth_backup.dart
    - lib/firebase_options_old_backup.dart
    - lib/providers/auth_provider.dart
    - lib/providers/beauty_*.dart
    - lib/screens/beauty_*.dart
    - lib/widgets/beauty_*.dart
    - lib/services/api_service.dart
    - lib/services/chat_service.dart
    - lib/services/history_service.dart
    - lib/services/inventory_service.dart
    - test/widget_test.dart

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
